### ISSUE TITLE
 On http://molgenis.github.io main page I have to click twice to search 

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis.org#43]
#### Reproduce

Go to http://molgenis.github.io/ and click on the searchbox in the upper right corner
#### Expected

After clicking on the search box I can directly type in my query 
#### Observed

It opens up a box to type my search in but I have to click on that box to be able to type

**Comment by sidohaakma** [comment]
The new site now is https://www.molgenis.org or molgenis.org.

For PR's please view: https://site.dev.molgenis.org
