### ISSUE TITLE
Documentation for installing cargo should be updated

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis.org#61]
http://molgenis.github.io/download#1usingmavencargo

Maven needs to be installed and mysql should be replaced with postgresql, localhost:8080 should be opened to see molgenis running. Password can be changed in molgenis server properties in source/main/resources. It is by default: admin, secret

**Comment by marikaris** [comment]
this is hanging on the issue that the outdated version is located in http://molgenis.github.io/download and the updated version here; http://molgenis.github.io/documentation/install no idea why this happened and why there is no link to the updated version. When this link is available it would be handy to update the cargo docs

**Comment by Mark-de-Haan** [comment]
Documentation was updated and moved to the MOLGENIS master repository
